Repository DivaryOfficial/divary-spring, pull requests merged in 2025-07, with the labels that each got.

#9 feat/#8: workflow 수정
  .github/workflows/dev_deploy.yml
  README.md
  src/main/java/com/divary/domain/system/controller/SystemController.java
  src/main/java/com/divary/global/config/WebConfig.java
  src/main/java/com/divary/global/exception/ErrorCode.java
  src/main/java/com/divary/global/exception/GlobalExceptionHandler.java
  src/main/java/com/divary/global/intercepter/LoggingInterceptor.java
  src/main/resources/logback-spring.xml
Labels: enhancement

#24 Feat/#20 21 22 entities pagination dto
  README.md
  src/main/java/com/divary/common/dto/BasePaginationDto.java
  src/main/java/com/divary/common/response/PagedResponse.java
  src/main/java/com/divary/domain/chatroom/entity/ChatRoom.java
  src/main/java/com/divary/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/divary/domain/image/entity/Image.java
  src/main/java/com/divary/domain/image/entity/ImageType.java
Labels: documentation, enhancement

#37 fix : publicId 관련 repository 삭제
  src/main/java/com/divary/common/response/PagedResponse.java
  src/main/java/com/divary/domain/chatroom/repository/ChatRoomRepository.java
Labels: bug

#38 feat/#34:로그북 엔티티 작성
  src/main/java/com/divary/domain/logbook/entity/Companion.java
  src/main/java/com/divary/domain/logbook/entity/LogBook.java
  src/main/java/com/divary/domain/logbook/enums/CompanionType.java
  src/main/java/com/divary/domain/logbook/enums/DiveMethod.java
  src/main/java/com/divary/domain/logbook/enums/DivePurpose.java
  src/main/java/com/divary/domain/logbook/enums/IconType.java
  src/main/java/com/divary/domain/logbook/enums/PerceiveTemp.java
  src/main/java/com/divary/domain/logbook/enums/PerceiveWeight.java
  src/main/java/com/divary/domain/logbook/enums/Sight.java
  src/main/java/com/divary/domain/logbook/enums/SuitType.java
  src/main/java/com/divary/domain/logbook/enums/Tide.java
  src/main/java/com/divary/domain/logbook/enums/Wave.java
  src/main/java/com/divary/domain/logbook/enums/WeatherType.java
  src/main/java/com/divary/domain/logbook/enums/Wind.java
Labels: enhancement

#39 feat/#32: encyclopedia 관련 api 구현
  src/main/java/com/divary/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/divary/domain/encyclopedia/controller/EncyclopediaCardController.java
  src/main/java/com/divary/domain/encyclopedia/dto/AppearanceResponse.java
  src/main/java/com/divary/domain/encyclopedia/dto/EncyclopediaCardResponse.java
  src/main/java/com/divary/domain/encyclopedia/dto/EncyclopediaCardSummaryResponse.java
  src/main/java/com/divary/domain/encyclopedia/dto/PersonalityResponse.java
  src/main/java/com/divary/domain/encyclopedia/dto/SignificantResponse.java
  src/main/java/com/divary/domain/encyclopedia/embedded/Appearance.java
  src/main/java/com/divary/domain/encyclopedia/embedded/Personality.java
  src/main/java/com/divary/domain/encyclopedia/embedded/Significant.java
  src/main/java/com/divary/domain/encyclopedia/entity/EncyclopediaCard.java
  src/main/java/com/divary/domain/encyclopedia/enums/Type.java
  src/main/java/com/divary/domain/encyclopedia/repository/EncyclopediaCardRepository.java
  src/main/java/com/divary/domain/encyclopedia/service/EncyclopediaCardService.java
  src/main/java/com/divary/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: enhancement

#49 feat/#47 : 알림 조회 기능 추가 //임시로 userId 하드코딩
  src/main/java/com/divary/domain/notification/controller/NotificationController.java
  src/main/java/com/divary/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/divary/domain/notification/repository/NotificationRepository.java
  src/main/java/com/divary/domain/notification/service/NotificationService.java
Labels: enhancement

#52 Feat/merge create chatroom to develop
  .github/workflows/dev_deploy.yml
Labels: documentation, enhancement

#57 Feat/#50 로그북 GET 관련 API 구현
  src/main/java/com/divary/domain/logbook/controller/LogBookController.java
  src/main/java/com/divary/domain/logbook/dto/LogBookRequestDTO.java
  src/main/java/com/divary/domain/logbook/dto/LogBookResponseDTO.java
  src/main/java/com/divary/domain/logbook/dto/request/CompanionRequestDTO.java
  src/main/java/com/divary/domain/logbook/dto/request/LogBaseCreateRequestDTO.java
  src/main/java/com/divary/domain/logbook/dto/request/LogDetailCreateRequestDTO.java
  src/main/java/com/divary/domain/logbook/dto/response/CompanionResultDTO.java
  src/main/java/com/divary/domain/logbook/dto/response/LogBaseCreateResultDTO.java
  src/main/java/com/divary/domain/logbook/dto/response/LogBaseListResultDTO.java
  src/main/java/com/divary/domain/logbook/dto/response/LogBookDetailResultDTO.java
  src/main/java/com/divary/domain/logbook/dto/response/LogDetailCreateResultDTO.java
  src/main/java/com/divary/domain/logbook/entity/LogBaseInfo.java
  src/main/java/com/divary/domain/logbook/entity/LogBook.java
  src/main/java/com/divary/domain/logbook/enums/IconType.java
  src/main/java/com/divary/domain/logbook/enums/SaveStatus.java
  src/main/java/com/divary/domain/logbook/repository/CompanionRepository.java
  src/main/java/com/divary/domain/logbook/repository/LogBaseInfoRepository.java
  src/main/java/com/divary/domain/logbook/repository/LogBookRepository.java
  src/main/java/com/divary/domain/logbook/service/LogBookService.java
  src/main/java/com/divary/global/exception/ErrorCode.java
Labels: enhancement

#68 feat/#67: avatar 생성 로직 추가, 특수 문자 사용 제한
  src/main/java/com/divary/domain/avatar/dto/AvatarRequestDTO.java
  src/main/java/com/divary/domain/avatar/entity/Avatar.java
  src/main/java/com/divary/domain/avatar/service/AvatarService.java
  src/main/java/com/divary/domain/avatar/service/AvatarServiceImpl.java
  src/main/java/com/divary/global/oauth/service/social/GoogleOauth.java
Labels: enhancement

#70 [FEATURE] Chat 도메인 @AuthenticationPrincipal를 통한 인증 절차 추가, 스웨거 문서 업데이트, 테스트 토큰 및 유저
  src/main/java/com/divary/common/response/ApiResponse.java
  src/main/java/com/divary/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/divary/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/divary/domain/system/controller/SystemController.java
  src/main/java/com/divary/global/config/SwaggerConfig.java
  src/main/java/com/divary/global/config/security/CustomUserDetailsService.java
  src/main/java/com/divary/global/config/security/CustomUserPrincipal.java
  src/main/java/com/divary/global/config/security/SecurityConfig.java
  src/main/java/com/divary/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/divary/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/divary/global/exception/ErrorCode.java
  src/main/java/com/divary/global/exception/GlobalExceptionHandler.java
Labels: documentation, enhancement

#79 [FEATURE] 이미지 임시 경로 업로드
  src/main/java/com/divary/domain/image/controller/ImageController.java
  src/main/java/com/divary/domain/image/dto/response/MultipleImageUploadResponse.java
  src/main/java/com/divary/domain/image/entity/Image.java
  src/main/java/com/divary/domain/image/entity/ImageType.java
  src/main/java/com/divary/domain/image/repository/ImageRepository.java
  src/main/java/com/divary/domain/image/service/ImageService.java
  src/main/java/com/divary/domain/image/service/ImageStorageService.java
  src/main/java/com/divary/domain/system/controller/SystemController.java
  src/main/java/com/divary/global/config/security/SecurityConfig.java
Labels: 📝 documentation, ✨ feature

#86 [FEATURE] 게시글 업데이트 시 이미지 업데이트
  .gitignore
  src/main/java/com/divary/DivaryApplication.java
  src/main/java/com/divary/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/divary/domain/encyclopedia/service/EncyclopediaCardService.java
  src/main/java/com/divary/domain/image/controller/ImageController.java
  src/main/java/com/divary/domain/image/dto/response/ImageResponse.java
  src/main/java/com/divary/domain/image/entity/Image.java
  src/main/java/com/divary/domain/image/enums/ImageType.java
  src/main/java/com/divary/domain/image/repository/ImageRepository.java
  src/main/java/com/divary/domain/image/service/ImageCleanupService.java
  src/main/java/com/divary/domain/image/service/ImagePathService.java
  src/main/java/com/divary/domain/image/service/ImageService.java
  src/main/java/com/divary/domain/image/service/ImageStorageService.java
  src/main/java/com/divary/domain/image/service/ImageValidationService.java
  src/main/java/com/divary/domain/logbook/entity/LogBaseInfo.java
  src/main/java/com/divary/domain/system/controller/SystemController.java
  src/main/java/com/divary/global/exception/ErrorCode.java
Labels: 📝 documentation, ✨ feature, ♻️ refactor
