Repository DivaryOfficial/divary-spring, pull requests merged in 2025-08, with the labels that each got.

#78 feat/#77- 알림 열람 true로 변경
  src/main/java/com/divary/domain/notification/controller/NotificationController.java
  src/main/java/com/divary/domain/notification/dto/NotificationPatchRequestDTO.java
  src/main/java/com/divary/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/divary/domain/notification/entity/Notification.java
  src/main/java/com/divary/domain/notification/repository/NotificationRepository.java
  src/main/java/com/divary/domain/notification/service/NotificationService.java
Labels: ✨ feature

#76 feat/#75: 자격증 이미지 등록 및 레벨 패치
  src/main/java/com/divary/domain/Member/enums/Level.java
  src/main/java/com/divary/domain/Member/enums/Role.java
  src/main/java/com/divary/domain/Member/service/MemberService.java
  src/main/java/com/divary/domain/Member/service/MemberServiceImpl.java
  src/main/java/com/divary/domain/avatar/controller/AvatarController.java
  src/main/java/com/divary/domain/avatar/entity/Avatar.java
  src/main/java/com/divary/domain/avatar/repository/AvatarRepository.java
  src/main/java/com/divary/domain/avatar/service/AvatarService.java
  src/main/java/com/divary/domain/avatar/service/AvatarServiceImpl.java
  src/main/java/com/divary/domain/logbase/LogBaseInfo.java
  src/main/java/com/divary/domain/logbase/LogBaseInfoRepository.java
  src/main/java/com/divary/domain/logbase/logbook/repository/LogBookRepository.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
  src/main/java/com/divary/domain/member/controller/MemberController.java
  src/main/java/com/divary/domain/member/dto/requestDTO/MyPageLevelRequestDTO.java
  src/main/java/com/divary/domain/member/dto/response/MyPageImageResponseDTO.java
  src/main/java/com/divary/domain/member/entity/Member.java
  src/main/java/com/divary/domain/member/enums/Levels.java
  src/main/java/com/divary/domain/member/enums/Role.java
  src/main/java/com/divary/domain/member/repository/MemberRepository.java
  src/main/java/com/divary/domain/member/service/MemberService.java
  src/main/java/com/divary/domain/member/service/MemberServiceImpl.java
  src/main/java/com/divary/domain/notification/controller/NotificationController.java
  src/main/java/com/divary/domain/notification/entity/Notification.java
  src/main/java/com/divary/domain/notification/repository/NotificationRepository.java
  src/main/java/com/divary/domain/notification/service/NotificationService.java
  src/main/java/com/divary/domain/system/controller/SystemController.java
  src/main/java/com/divary/global/config/security/CustomUserDetailsService.java
  src/main/java/com/divary/global/config/security/CustomUserPrincipal.java
  src/main/java/com/divary/global/oauth/dto/LoginResponseDTO.java
  src/main/java/com/divary/global/oauth/service/social/GoogleOauth.java
  src/main/resources/templates/index.html
Labels: ✨ feature

#82 Feat/#81 change bubble enum buddy enum
  src/main/java/com/divary/domain/avatar/controller/AvatarController.java
  src/main/java/com/divary/domain/avatar/dto/AvatarRequestDTO.java
  src/main/java/com/divary/domain/avatar/dto/AvatarResponseDTO.java
  src/main/java/com/divary/domain/avatar/dto/BuddyPetInfoDTO.java
  src/main/java/com/divary/domain/avatar/entity/Avatar.java
  src/main/java/com/divary/domain/avatar/enums/BudyPet.java
  src/main/java/com/divary/domain/avatar/enums/CheekColor.java
  src/main/java/com/divary/domain/avatar/enums/Mask.java
  src/main/java/com/divary/domain/avatar/enums/Pin.java
  src/main/java/com/divary/domain/avatar/enums/Regulator.java
  src/main/java/com/divary/domain/avatar/enums/SpeechBubble.java
  src/main/java/com/divary/domain/avatar/enums/Tank.java
  src/main/java/com/divary/domain/avatar/repository/AvatarRepository.java
  src/main/java/com/divary/domain/avatar/service/AvatarService.java
  src/main/java/com/divary/domain/avatar/service/AvatarServiceImpl.java
  src/main/java/com/divary/domain/notification/repository/NotificationRepository.java
  src/main/java/com/divary/domain/notification/service/NotificationService.java
  src/main/java/com/divary/global/oauth/service/social/GoogleOauth.java
Labels: ✨ feature

#98 fix: 도감 카드 목록 조회 시 이미지가 누락되는 문제 해결
  src/main/java/com/divary/domain/encyclopedia/service/EncyclopediaCardService.java
  src/main/java/com/divary/domain/image/controller/ImageController.java
  src/main/java/com/divary/domain/image/dto/response/ImageResponse.java
  src/main/java/com/divary/domain/image/service/ImageService.java
Labels: 🐛 bug

#96 fix/#94:로그북 put request dto 수정
  src/main/java/com/divary/domain/logbase/logbook/dto/request/LogDetailPutRequestDTO.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
Labels: 🐛 bug

#106 fix: 도감 상세 조회 이미지 경로 오류 수정 및 gitignore 추가
  .gitignore
  src/main/java/com/divary/domain/encyclopedia/service/EncyclopediaCardService.java
Labels: 🐛 bug

#104 fix: 다이어리 저장 시 임시 이미지가 영구 전환되지 않는 문제 해결
  src/main/java/com/divary/domain/image/entity/Image.java
  src/main/java/com/divary/domain/image/enums/ImageType.java
  src/main/java/com/divary/domain/logbase/logdiary/controller/DiaryController.java
  src/main/java/com/divary/domain/logbase/logdiary/dto/DiaryResponse.java
  src/main/java/com/divary/domain/logbase/logdiary/service/DiaryService.java
Labels: 🐛 bug

#114 Fix/#112 : 로그북 조회시 null 값 반환 처리
  src/main/java/com/divary/domain/logbase/logbook/dto/response/LogBaseCreateResultDTO.java
  src/main/java/com/divary/domain/logbase/logbook/dto/response/LogBookDetailResultDTO.java
  src/main/java/com/divary/domain/logbase/logbook/entity/LogBook.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
Labels: 🐛 bug

#116 [MERGE] DEVELOP TO MAIN
  src/main/java/com/divary/domain/avatar/service/AvatarServiceImpl.java
  src/main/java/com/divary/domain/logbase/logbook/dto/response/LogBaseCreateResultDTO.java
  src/main/java/com/divary/domain/logbase/logbook/dto/response/LogBookDetailResultDTO.java
  src/main/java/com/divary/domain/logbase/logbook/entity/LogBook.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
Labels: 🚀 deploy

#120 refac/#118: 누적횟수 계산 로직 변경
  src/main/java/com/divary/domain/logbase/logbook/controller/LogBookController.java
  src/main/java/com/divary/domain/logbase/logbook/dto/response/LogBookDetailResultDTO.java
  src/main/java/com/divary/domain/logbase/logbook/entity/LogBook.java
  src/main/java/com/divary/domain/logbase/logbook/repository/LogBookRepository.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
Labels: ♻️ refactor

#126 Fix #104 #106 pr 복구
  .gitignore
  src/main/java/com/divary/domain/encyclopedia/service/EncyclopediaCardService.java
  src/main/java/com/divary/domain/image/entity/Image.java
  src/main/java/com/divary/domain/image/enums/ImageType.java
  src/main/java/com/divary/domain/logbase/logdiary/controller/DiaryController.java
  src/main/java/com/divary/domain/logbase/logdiary/dto/DiaryResponse.java
  src/main/java/com/divary/domain/logbase/logdiary/service/DiaryService.java
Labels: 🐛 bug

#128 [MERGE] DEVELOP TO MAIN
  build.gradle
  src/main/java/com/divary/DivaryApplication.java
  src/main/java/com/divary/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/divary/domain/encyclopedia/service/EncyclopediaCardService.java
  src/main/java/com/divary/domain/image/controller/ImageController.java
  src/main/java/com/divary/domain/image/entity/Image.java
  src/main/java/com/divary/domain/image/service/ImagePathService.java
  src/main/java/com/divary/domain/image/service/ImageService.java
  src/main/java/com/divary/domain/image/service/ImageValidationService.java
  src/main/java/com/divary/domain/logbase/logbook/repository/LogBookRepository.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
  src/main/java/com/divary/domain/member/service/MemberServiceImpl.java
  src/main/java/com/divary/global/config/CacheConfig.java
  src/main/resources/application.yml
  src/main/resources/logbook-enums.txt
  src/test/java/com/divary/integration/ImageDiaryFlowApiTest.java
Labels: 🐛 bug, 🚀 deploy

#123 refac/#122: cheek null가능하게 수정
  src/main/java/com/divary/domain/avatar/dto/AvatarRequestDTO.java
  src/main/java/com/divary/domain/avatar/entity/Avatar.java
  src/main/java/com/divary/domain/avatar/enums/Mask.java
  src/main/java/com/divary/domain/avatar/enums/Pin.java
  src/main/java/com/divary/domain/avatar/enums/Regulator.java
  src/main/java/com/divary/domain/avatar/enums/Tank.java
Labels: ♻️ refactor

#133 feat/#131: log date patch api 구현
  src/main/java/com/divary/domain/logbase/logbook/controller/LogBookController.java
  src/main/java/com/divary/domain/logbase/logbook/dto/request/LogDateUpdateRequestDTO.java
  src/main/java/com/divary/domain/logbase/logbook/dto/request/LogDetailPutRequestDTO.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
Labels: ✨ feature

#139 refac/#135: 로그베이스 날짜 수정 api 검증 로직 추가
  src/main/java/com/divary/domain/logbase/logbook/controller/LogBookController.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
  src/main/java/com/divary/global/exception/ErrorCode.java
Labels: ♻️ refactor

#147 feat/#142:로그베이스 리스트 전체 조회 api
  src/main/java/com/divary/domain/logbase/LogBaseInfoRepository.java
  src/main/java/com/divary/domain/logbase/logbook/controller/LogBookController.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
Labels: ✨ feature

#148 Develop
  src/main/java/com/divary/domain/encyclopedia/controller/EncyclopediaCardController.java
  src/main/java/com/divary/domain/logbase/LogBaseInfoRepository.java
  src/main/java/com/divary/domain/logbase/logbook/controller/LogBookController.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
  src/main/java/com/divary/global/oauth/controller/OauthController.java
Labels: ✨ feature

#156 fix/#155:로그 저장상태 오류 수정
  src/main/java/com/divary/domain/logbase/logbook/repository/LogBookRepository.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
Labels: 🐛 bug

#157 Develop
  src/main/java/com/divary/domain/logbase/logbook/repository/LogBookRepository.java
  src/main/java/com/divary/domain/logbase/logbook/service/LogBookService.java
Labels: 🚀 deploy
